# Here we are predict the message is depressed or not depressed based on messages

## Domain Analysis

In [56]:
import pandas as pd  # use for data Analysis
import numpy as np  # use for Mising value handle
import matplotlib.pyplot as plt  # use for data visualization
import seaborn as sns # use for data visualization

In [57]:
# load the Dataset
data = pd.read_csv("sentiment_tweets3.csv")
data

Index                                 message to examine  \
0         106  just had a real good moment. i missssssssss hi...   
1         217         is reading manga  http://plurk.com/p/mzp1e   
2         220  @comeagainjen http://twitpic.com/2y2lx - http:...   
3         288  @lapcat Need to send 'em to my accountant tomo...   
4         540      ADD ME ON MYSPACE!!!  myspace.com/LookThunder   
...       ...                                                ...   
10309  802309  No Depression by G Herbo is my mood from now o...   
10310  802310  What do you do when depression succumbs the br...   
10311  802311  Ketamine Nasal Spray Shows Promise Against Dep...   
10312  802312  dont mistake a bad day with depression! everyo...   
10313  802313                                                  0   

       label (depression result)  
0                              0  
1                              0  
2                              0  
3                              0  
4                              0  
...                          ...  
10309                          1  
10310                          1  
10311                          1  
10312                          1  
10313                          1  

[10314 rows x 3 columns]

### Bussiness Analysis:-
* Here we are use the sentiment twitter message analysis and predict the message is depressed or not depressed based on message.
* There is Sentiment Twitter Dataset or different column like index, message, label. 

### Domain Analysis:-
#### Atrribute Information:-
* Index:-  The row number or unique identifier for each tweet or message. This helps in locating specific entries.

* message_to_examine:-  This column likely contains the text of the tweet or the message that you are analyzing. It could be raw text data pulled directly from Twitter posts.

* label:-  The label indicates the classification or outcome of each message. For example, in a dataset related to mental health, the label might indicate whether the message shows signs of depression (1 for depressed, 0 for not depressed).

* Length:-  This column could represent the number of characters in each tweet. Tweets are typically limited in length (up to 280 characters), so this can be useful for analyzing tweet structure and brevity.

## Basic Check

In [58]:
data.head() # showning the top 5 rows data

Index                                 message to examine  \
0    106  just had a real good moment. i missssssssss hi...   
1    217         is reading manga  http://plurk.com/p/mzp1e   
2    220  @comeagainjen http://twitpic.com/2y2lx - http:...   
3    288  @lapcat Need to send 'em to my accountant tomo...   
4    540      ADD ME ON MYSPACE!!!  myspace.com/LookThunder   

   label (depression result)  
0                          0  
1                          0  
2                          0  
3                          0  
4                          0

In [59]:
data.tail() # showning the last 5 rows data 

Index                                 message to examine  \
10309  802309  No Depression by G Herbo is my mood from now o...   
10310  802310  What do you do when depression succumbs the br...   
10311  802311  Ketamine Nasal Spray Shows Promise Against Dep...   
10312  802312  dont mistake a bad day with depression! everyo...   
10313  802313                                                  0   

       label (depression result)  
10309                          1  
10310                          1  
10311                          1  
10312                          1  
10313                          1

In [60]:
# change to the column name
data.rename(columns={"message to examine": "message_to_examine", "label (depression result)": "label"}, inplace=True)

In [61]:
data.head() # showning the top 5 rows data

Index                                 message_to_examine  label
0    106  just had a real good moment. i missssssssss hi...      0
1    217         is reading manga  http://plurk.com/p/mzp1e      0
2    220  @comeagainjen http://twitpic.com/2y2lx - http:...      0
3    288  @lapcat Need to send 'em to my accountant tomo...      0
4    540      ADD ME ON MYSPACE!!!  myspace.com/LookThunder      0

In [62]:
data.describe(include="O") # show the 

message_to_examine
count                                               10314
unique                                              10282
top     Mom's depression tied to kids' emotional, inte...
freq                                                   11

In [63]:
data.info() # use for see the dataset details

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10314 entries, 0 to 10313
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Index               10314 non-null  int64 
 1   message_to_examine  10314 non-null  object
 2   label               10314 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 241.9+ KB


In [64]:
# check the message length and create new column
data["Length"] = data["message_to_examine"].apply(len)

In [65]:
data.head()  # showning the last 5 rows data

Index                                 message_to_examine  label  Length
0    106  just had a real good moment. i missssssssss hi...      0      57
1    217         is reading manga  http://plurk.com/p/mzp1e      0      42
2    220  @comeagainjen http://twitpic.com/2y2lx - http:...      0      84
3    288  @lapcat Need to send 'em to my accountant tomo...      0     135
4    540      ADD ME ON MYSPACE!!!  myspace.com/LookThunder      0      45

In [66]:
# drop the unknown digit in message column
data.drop(index=[9606, 10313], inplace=True)

In [67]:
np.max(data["Length"]) # check the maximum length index

874

In [68]:
data.iloc[874,1] # check the maximum length message

"Good Sunday Morning! It's raining again so I'm going to make some potato soup for dinner and the rest of the day will be lazy day. "

In [69]:
data.label.value_counts()

label
0    8000
1    2312
Name: count, dtype: int64

In [70]:
# drop the index column
data.drop("Index",axis=1,inplace=True)

In [71]:
data.head()  # showning the last 5 rows data

message_to_examine  label  Length
0  just had a real good moment. i missssssssss hi...      0      57
1         is reading manga  http://plurk.com/p/mzp1e      0      42
2  @comeagainjen http://twitpic.com/2y2lx - http:...      0      84
3  @lapcat Need to send 'em to my accountant tomo...      0     135
4      ADD ME ON MYSPACE!!!  myspace.com/LookThunder      0      45

## Data Preprocessning

In [72]:
import string # import the string
string.punctuation  # use for punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [73]:
# create function and remove special character and convert the text in lower case 
def remove_punc(text):
    text = "".join([char for char in text if char not in string.punctuation])
    return text.lower()

In [74]:
# check the function
a = "Hello@#@"
remove_punc(a)

'hello'

In [75]:
# remove the punctuation and store the value in text
text = []
for i in data["message_to_examine"]:
    t = remove_punc(i)
    text.append(t)

In [76]:
# use for create the columnn and store the data
data["Text_Clean"] = text

In [77]:
data.head()  # showning the last 5 rows data

message_to_examine  label  Length  \
0  just had a real good moment. i missssssssss hi...      0      57   
1         is reading manga  http://plurk.com/p/mzp1e      0      42   
2  @comeagainjen http://twitpic.com/2y2lx - http:...      0      84   
3  @lapcat Need to send 'em to my accountant tomo...      0     135   
4      ADD ME ON MYSPACE!!!  myspace.com/LookThunder      0      45   

                                          Text_Clean  
0  just had a real good moment i missssssssss him...  
1               is reading manga  httpplurkcompmzp1e  
2  comeagainjen httptwitpiccom2y2lx  httpwwwyoutu...  
3  lapcat need to send em to my accountant tomorr...  
4           add me on myspace  myspacecomlookthunder

In [78]:
x = data["Text_Clean"].values # store the input variable
y = data["label"].values # store the Output variable

In [79]:
x # input variable

array(['just had a real good moment i missssssssss him so much ',
       'is reading manga  httpplurkcompmzp1e',
       'comeagainjen httptwitpiccom2y2lx  httpwwwyoutubecomwatchvzogfqvh2me8 ',
       ...,
       'what do you do when depression succumbs the brain and makes you feel like youll never be enough',
       'ketamine nasal spray shows promise against depression suicide health httpscmunit4sjligkâ\xa0',
       'dont mistake a bad day with depression everyone has em'],
      dtype=object)

In [80]:
y # Output variable

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

## Multinominal Model Evaluation

In [81]:
from sklearn.model_selection import train_test_split # use for the split the data in traning and testing
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=40)

In [82]:
x_train.shape # check the training shape

(7734,)

In [83]:
x_test.shape # check the testing shape

(2578,)

In [84]:
# use for convert categorical to numerical
from sklearn.feature_extraction.text import CountVectorizer

In [85]:
CV = CountVectorizer(stop_words="english") # remove the grammerical words

In [86]:
x_train_cv = CV.fit_transform(x_train) # training data transfer to the countvectore

In [87]:
x_train_cv # check the transfer 

<7734x18985 sparse matrix of type '<class 'numpy.int64'>'
	with 62149 stored elements in Compressed Sparse Row format>

In [88]:
# import the mutinominal classifiers
from sklearn.naive_bayes import MultinomialNB 

In [89]:
NBC = MultinomialNB() # Store the Algorithm in variable

In [90]:
NBC.fit(x_train_cv,y_train) # train the model

MultinomialNB()

In [91]:
x_test_cv = CV.transform(x_test)

In [92]:
y_predict = NBC.predict(x_test_cv)

In [93]:
y_predict

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [94]:
# import the metrics and use for check model performance
from sklearn.metrics import accuracy_score,f1_score,classification_report,confusion_matrix

In [95]:
accuracy_score(y_test,y_predict) * 100 # check the model accuracy

97.78898370830102

In [96]:
f1_score(y_test,y_predict,average="weighted") # check the traning model performence

0.9780272868843249

In [97]:
print(classification_report(y_test,y_predict)) # check to the model performance report 

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      1996
           1       0.94      0.97      0.95       582

    accuracy                           0.98      2578
   macro avg       0.96      0.97      0.97      2578
weighted avg       0.98      0.98      0.98      2578



In [98]:
confusion_matrix(y_test,y_predict) # check the model true and False predict number

array([[1957,   39],
       [  18,  564]], dtype=int64)

## Bernoulli Model Evaluation

In [99]:
from sklearn.feature_extraction.text import TfidfVectorizer # import tf vectore

In [100]:
tfv = TfidfVectorizer() # store the tf vectore

In [101]:
x = tfv.fit_transform(x) # tranform the x in tfv vectore

In [102]:
x.shape # check the x shape

(10312, 23722)

In [103]:
x = x.toarray() # covert to array

In [104]:
x # check the convert to array

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [109]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [111]:
# split the data into traning and testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=40)

In [112]:
x_train.shape # checkt the shape

(7734, 23722)

In [113]:
x_test.shape # checkt the shape

(2578, 23722)

In [114]:
from sklearn.naive_bayes import BernoulliNB # import the bernoulliNB 

In [115]:
BNB = BernoulliNB() # store the model 

In [116]:
BNB.fit(x_train,y_train) # train the model 

BernoulliNB()

In [117]:
y_bnmpredict = BNB.predict(x_test) # predict the test

In [118]:
accuracy_score(y_test,y_bnmpredict) # check the model accuracy

0.9356089992242048

In [120]:
f1_score(y_test,y_bnmpredict,average="weighted") # check the traning score 

0.9315391780803598

In [121]:
print(classification_report(y_test,y_bnmpredict)) # check the model performance report 

              precision    recall  f1-score   support

           0       0.92      1.00      0.96      1996
           1       1.00      0.71      0.83       582

    accuracy                           0.94      2578
   macro avg       0.96      0.86      0.90      2578
weighted avg       0.94      0.94      0.93      2578



In [122]:
confusion_matrix(y_test,y_bnmpredict) # check the True false value 

array([[1996,    0],
       [ 166,  416]], dtype=int64)

## Final Conclusion:-
* Multinominal Model accuracy is 97.78 and Traning performance is 97.80

## Check the model and Predict output

In [102]:
msg = input("Enter Message: ") # to get the input message
msgInput = CV.transform([msg]) # tranform the message
predict = NBC.predict(msgInput) # predict the message
if(predict[0]==0): # check the condition
    print("------------------------MESSAGE-SENT-[NOT-DEPRESSED]---------------------------")
else:
    print("---------------------------MESSAGE-SENT-[DEPRESSED]------------------------------")

Enter Message:  "I can’t remember the last time I felt genuinely happy."


------------------------MESSAGE-SENT-[NOT-DEPRESSED]---------------------------


In [97]:
data.head(8001) # showning the index number 80001 message

message_to_examine  label  Length  \
0     just had a real good moment. i missssssssss hi...      0      57   
1            is reading manga  http://plurk.com/p/mzp1e      0      42   
2     @comeagainjen http://twitpic.com/2y2lx - http:...      0      84   
3     @lapcat Need to send 'em to my accountant tomo...      0     135   
4         ADD ME ON MYSPACE!!!  myspace.com/LookThunder      0      45   
...                                                 ...    ...     ...   
7996  @theokk don't know what you could possibly mea...      0      64   
7997  @shwood loved the cameo, made me chuckle! alon...      0      98   
7998  lol. i just realized my room has a color theme...      0     132   
7999                  ReCoVeRiNg FrOm ThE lOnG wEeKeNd       0      33   
8000  The lack of this understanding is a small but ...      1     215   

                                             Text_Clean  
0     just had a real good moment i missssssssss him...  
1                  is reading manga  httpplurkcompmzp1e  
2     comeagainjen httptwitpiccom2y2lx  httpwwwyoutu...  
3     lapcat need to send em to my accountant tomorr...  
4              add me on myspace  myspacecomlookthunder  
...                                                 ...  
7996  theokk dont know what you could possibly mean ...  
7997  shwood loved the cameo made me chuckle along w...  
7998  lol i just realized my room has a color theme ...  
7999                  recovering from the long weekend   
8000  the lack of this understanding is a small but ...  

[8001 rows x 4 columns]

In [98]:
data.iloc[8000,0] # check the index number message

"The lack of this understanding is a small but significant part of what causes anxiety & depression to both feel so incredibly lonely. It's soooo easy to compare. It's so easy to invalidate ourselves because of that."

                                                            ! Thank You !